version: "4.38"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - redis_password=${redis_password}
      - redis_user=${redis_user}
      - redis_user_password=${redis_user_password}
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf
        echo "requirepass $redis_password" >> /usr/local/etc/redis/redis.conf
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl
        echo "user $redis_user on >$redis_user_password ~* +@all" >> /usr/local/etc/redis/users.acl
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$redis_password", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true